# Generated by Django 2.2.16 on 2023-05-04 13:39

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20230504_1620'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='not_self',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('author')), name='not_self'),
        ),
    ]
